version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
    environment:
      WP_NAME: ${WP_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_DBUSER: ${WP_DBUSER}
      WP_EMAIL: ${WP_EMAIL}
      WP_PASSWORD: ${WP_PASSWORD}

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    ports:
    - "3306:3306"
    environment:
      MYSQL_DBNAME: ${DB_NAME}
      MYSQL_USER: ${DB_ADMIN}
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
# volumes:
#   db_data:
#     driver: local
#   web_data:
#     driver: local
#   nginx_data:
#     driver: local
#   wordpress_data: 
#     driver: local
#   mariadb_data:
#     driver: local
# networks:   
#   default:
#     driver: bridge
#     name: wp_network