server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name ngoyat.42.fr;
    root /var/www/html;
    index index.php index.html index.htm;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wp-php:9000;
    }

    location ~ /\.ht {
        deny all;
    }
}